# application-prod.yml

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      initialization-fail-timeout: 0
      auto-commit: false
      pool-name: CampusAddaHikariPool

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: none

    show-sql: false

    properties:
      hibernate:
        format_sql: false

        jdbc:
          time_zone: UTC
          batch_size: 20

        order_inserts: true
        order_updates: true

        temp:
          use_jdbc_metadata_defaults: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

  main:
    lazy-initialization: true

server:
  port: ${PORT:8081}

  tomcat:
    threads:
      max: 20
      min-spare: 2

logging:
  level:
    root: info
    org.hibernate.SQL: warn
    org.springframework: warn

app:
  kafka:
    enabled: false