
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: validate

    show-sql: false

    properties:
      hibernate:
        format_sql: false

        jdbc:
          time_zone: UTC
          batch_size: 20

        order_inserts: true
        order_updates: true

        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

server:
  tomcat:
    threads:
      max: 20
      min-spare: 2

logging:
  level:
    root: info
    org.hibernate.SQL: warn

app:
  kafka:
    enabled: false

